spring:
  application:
    name: ipinfo-local-service
  profiles:
    active: @activatedProperties@
  threads:
    virtual:
      enabled: true
server:
  port: ${SERVER_PORT:8080}
  tomcat:
    threads:
      max: 400
      min-spare: 20
    max-connections: 10000
    accept-count: 1000
    max-keep-alive-requests: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ipinfo: INFO
  health:
    probes:
      enabled: true		








  
