ipinfo:
  token: ${IPINFO_TOKEN:1234}
  database-path: ${IPINFO_DATABASE_PATH:./data/ipinfo_lite.mmdb}
  download-url: ${IPINFO_DOWNLOAD_URL:https://ipinfo.io/data/ipinfo_lite.mmdb}
  # Todos los días a las 06:00, hora Colombia.
  update-cron: ${IPINFO_UPDATE_CRON:0 0 6 * * *}
  update-zone: ${IPINFO_UPDATE_ZONE:America/Bogota}
  connect-timeout: ${IPINFO_CONNECT_TIMEOUT:10s}
  request-timeout: ${IPINFO_REQUEST_TIMEOUT:2m}
  minimum-file-size-bytes: ${IPINFO_MINIMUM_FILE_SIZE_BYTES:1000000}
  download-on-startup-when-missing: ${IPINFO_DOWNLOAD_ON_STARTUP_WHEN_MISSING:true}
  # configuracion de correos para notificaciones de fallos en la actualizacion de la base de datos
  mail-notification:
     enabled: ${IPINFO_MAIL_ENABLED:true}
     url: ${IPINFO_MAIL_URL:http://172.30.150.5:9092/api/clientapps/tucompraemail/enviarCorreoTuCompra}
     from: ${IPINFO_MAIL_FROM:monitoreo@tucompra.com.co}
     to: ${IPINFO_MAIL_TO:notificaciones@tucompra.com.co}
     subject: ${IPINFO_MAIL_SUBJECT:[ALERTA-DEMO] Fallo al actualizar base de datos IPinfo Lite}
